In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('reddit_rules_dataset_18krules.csv')

In [3]:
df.head()

,subreddit,sub_description,kind,priority,short_name,violation_reason,description,created_utc,rule_prompt
0,r/007,The world of Commander Bond CMG RNVR.,all,2,Never let them see you bleed.,Never let them see you bleed.,NaN,1710260006,Never let them see you bleed
1,r/007,The world of Commander Bond CMG RNVR.,all,3,Never get into a car with a strange girl.,Never get into a car with a strange girl.,NaN,1710260019,Never get into a car with a strange girl
2,r/00sAesthetics,Media culture from the Early 2000s (2000-2010)...,all,3,"No discriminatory, uncivil comments","No discriminatory, uncivil comments",NaN,1652978811,"No discriminatory, uncivil comments"
3,r/00sAesthetics,Media culture from the Early 2000s (2000-2010)...,all,4,No excessive self-promotion,No excessive self-promotion,NaN,1652978811,No excessive self-promotion
4,r/070Shake,The Official 070 Shake Subreddit!,all,1,No trolling or spamming.,No trolling or spamming.,NaN,1652979501,No trolling or spamming

In [4]:
df.columns

Index(['subreddit', 'sub_description', 'kind', 'priority', 'short_name',
       'violation_reason', 'description', 'created_utc', 'rule_prompt'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30670 entries, 0 to 30669
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   subreddit         30670 non-null  object
 1   sub_description   29895 non-null  object
 2   kind              30670 non-null  object
 3   priority          30670 non-null  int64
 4   short_name        30670 non-null  object
 5   violation_reason  30670 non-null  object
 6   description       25873 non-null  object
 7   created_utc       30670 non-null  int64
 8   rule_prompt       30670 non-null  object
dtypes: int64(2), object(7)
memory usage: 2.1+ MB

In [6]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of              subreddit                                    sub_description  \
0                r/007              The world of Commander Bond CMG RNVR.
1                r/007              The world of Commander Bond CMG RNVR.
2      r/00sAesthetics  Media culture from the Early 2000s (2000-2010)...
3      r/00sAesthetics  Media culture from the Early 2000s (2000-2010)...
4           r/070Shake                  The Official 070 Shake Subreddit!
...                ...                                                ...
30665   r/zulu_maidens  A community to share pictures and videos from ...
30666         r/zurich  A subreddit dedicated to Zürich and its greate...
30667         r/zurich  A subreddit dedicated to Zürich and its greate...
30668     r/zxspectrum  \nThe ZX Spectrum (pronounced "Zed-Ex" from it...
30669     r/zxspectrum  \nThe ZX Spectrum (pronounced "Zed-Ex" from it...

      kind  priority                                 short_name  \
0      all         2              Never let them see you bleed.
1      all         3  Never get into a car with a strange girl.
2      all         3        No discriminatory, uncivil comments
3      all         4                No excessive self-promotion
4      all         1                   No trolling or spamming.
...    ...       ...                                        ...
30665  all         2                                   No child
30666  all         0                          No misinformation
30667  all         1                        No personal attacks
30668  all         1                                    No spam
30669  all         2                            Don't be a dick

                                violation_reason  \
0                  Never let them see you bleed.
1      Never get into a car with a strange girl.
2            No discriminatory, uncivil comments
3                    No excessive self-promotion
4                       No trolling or spamming.
...                                          ...
30665                                   No child
30666                          No misinformation
30667                        No personal attacks
30668                                    No spam
30669                            Don't be a dick

                                             description  created_utc  \
0                                                    NaN   1710260006
1                                                    NaN   1710260019
2                                                    NaN   1652978811
3                                                    NaN   1652978811
4                                                    NaN   1652979501
...                                                  ...          ...
30665                                                NaN   1665742007
30666  No misinformation, conspiracies or blatant rumors   1704133469
30667                          Be nice and keep it civil   1652990494
30668  No more than 10 percent of your submissions sh...   1652980368
30669  Adhere to reddiquette and all of reddit's side...   1652980368

                                    rule_prompt
0                  Never let them see you bleed
1      Never get into a car with a strange girl
2           No discriminatory, uncivil comments
3                   No excessive self-promotion
4                       No trolling or spamming
...                                         ...
30665                                  No child
30666                         No misinformation
30667                       No personal attacks
30668                                   No spam
30669                           Don't be a dick

[30670 rows x 9 columns]>

In [7]:
df.dropna

<bound method DataFrame.dropna of              subreddit                                    sub_description  \
0                r/007              The world of Commander Bond CMG RNVR.
1                r/007              The world of Commander Bond CMG RNVR.
2      r/00sAesthetics  Media culture from the Early 2000s (2000-2010)...
3      r/00sAesthetics  Media culture from the Early 2000s (2000-2010)...
4           r/070Shake                  The Official 070 Shake Subreddit!
...                ...                                                ...
30665   r/zulu_maidens  A community to share pictures and videos from ...
30666         r/zurich  A subreddit dedicated to Zürich and its greate...
30667         r/zurich  A subreddit dedicated to Zürich and its greate...
30668     r/zxspectrum  \nThe ZX Spectrum (pronounced "Zed-Ex" from it...
30669     r/zxspectrum  \nThe ZX Spectrum (pronounced "Zed-Ex" from it...

      kind  priority                                 short_name  \
0      all         2              Never let them see you bleed.
1      all         3  Never get into a car with a strange girl.
2      all         3        No discriminatory, uncivil comments
3      all         4                No excessive self-promotion
4      all         1                   No trolling or spamming.
...    ...       ...                                        ...
30665  all         2                                   No child
30666  all         0                          No misinformation
30667  all         1                        No personal attacks
30668  all         1                                    No spam
30669  all         2                            Don't be a dick

                                violation_reason  \
0                  Never let them see you bleed.
1      Never get into a car with a strange girl.
2            No discriminatory, uncivil comments
3                    No excessive self-promotion
4                       No trolling or spamming.
...                                          ...
30665                                   No child
30666                          No misinformation
30667                        No personal attacks
30668                                    No spam
30669                            Don't be a dick

                                             description  created_utc  \
0                                                    NaN   1710260006
1                                                    NaN   1710260019
2                                                    NaN   1652978811
3                                                    NaN   1652978811
4                                                    NaN   1652979501
...                                                  ...          ...
30665                                                NaN   1665742007
30666  No misinformation, conspiracies or blatant rumors   1704133469
30667                          Be nice and keep it civil   1652990494
30668  No more than 10 percent of your submissions sh...   1652980368
30669  Adhere to reddiquette and all of reddit's side...   1652980368

                                    rule_prompt
0                  Never let them see you bleed
1      Never get into a car with a strange girl
2           No discriminatory, uncivil comments
3                   No excessive self-promotion
4                       No trolling or spamming
...                                         ...
30665                                  No child
30666                         No misinformation
30667                       No personal attacks
30668                                   No spam
30669                           Don't be a dick

[30670 rows x 9 columns]>

In [8]:
df.fillna(0)

,subreddit,sub_description,kind,priority,short_name,violation_reason,description,created_utc,rule_prompt
0,r/007,The world of Commander Bond CMG RNVR.,all,2,Never let them see you bleed.,Never let them see you bleed.,0,1710260006,Never let them see you bleed
1,r/007,The world of Commander Bond CMG RNVR.,all,3,Never get into a car with a strange girl.,Never get into a car with a strange girl.,0,1710260019,Never get into a car with a strange girl
2,r/00sAesthetics,Media culture from the Early 2000s (2000-2010)...,all,3,"No discriminatory, uncivil comments","No discriminatory, uncivil comments",0,1652978811,"No discriminatory, uncivil comments"
3,r/00sAesthetics,Media culture from the Early 2000s (2000-2010)...,all,4,No excessive self-promotion,No excessive self-promotion,0,1652978811,No excessive self-promotion
4,r/070Shake,The Official 070 Shake Subreddit!,all,1,No trolling or spamming.,No trolling or spamming.,0,1652979501,No trolling or spamming
...,...,...,...,...,...,...,...,...,...
30665,r/zulu_maidens,A community to share pictures and videos from ...,all,2,No child,No child,0,1665742007,No child
30666,r/zurich,A subreddit dedicated to Zürich and its greate...,all,0,No misinformation,No misinformation,"No misinformation, conspiracies or blatant rumors",1704133469,No misinformation
30667,r/zurich,A subreddit dedicated to Zürich and its greate...,all,1,No personal attacks,No personal attacks,Be nice and keep it civil,1652990494,No personal attacks
30668,r/zxspectrum,"\nThe ZX Spectrum (pronounced ""Zed-Ex"" from it...",all,1,No spam,No spam,No more than 10 percent of your submissions sh...,1652980368,No spam
30669,r/zxspectrum,"\nThe ZX Spectrum (pronounced ""Zed-Ex"" from it...",all,2,Don't be a dick,Don't be a dick,Adhere to reddiquette and all of reddit's side...,1652980368,Don't be a dick

In [9]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of              subreddit                                    sub_description  \
0                r/007              The world of Commander Bond CMG RNVR.
1                r/007              The world of Commander Bond CMG RNVR.
2      r/00sAesthetics  Media culture from the Early 2000s (2000-2010)...
3      r/00sAesthetics  Media culture from the Early 2000s (2000-2010)...
4           r/070Shake                  The Official 070 Shake Subreddit!
...                ...                                                ...
30665   r/zulu_maidens  A community to share pictures and videos from ...
30666         r/zurich  A subreddit dedicated to Zürich and its greate...
30667         r/zurich  A subreddit dedicated to Zürich and its greate...
30668     r/zxspectrum  \nThe ZX Spectrum (pronounced "Zed-Ex" from it...
30669     r/zxspectrum  \nThe ZX Spectrum (pronounced "Zed-Ex" from it...

      kind  priority                                 short_name  \
0      all         2              Never let them see you bleed.
1      all         3  Never get into a car with a strange girl.
2      all         3        No discriminatory, uncivil comments
3      all         4                No excessive self-promotion
4      all         1                   No trolling or spamming.
...    ...       ...                                        ...
30665  all         2                                   No child
30666  all         0                          No misinformation
30667  all         1                        No personal attacks
30668  all         1                                    No spam
30669  all         2                            Don't be a dick

                                violation_reason  \
0                  Never let them see you bleed.
1      Never get into a car with a strange girl.
2            No discriminatory, uncivil comments
3                    No excessive self-promotion
4                       No trolling or spamming.
...                                          ...
30665                                   No child
30666                          No misinformation
30667                        No personal attacks
30668                                    No spam
30669                            Don't be a dick

                                             description  created_utc  \
0                                                    NaN   1710260006
1                                                    NaN   1710260019
2                                                    NaN   1652978811
3                                                    NaN   1652978811
4                                                    NaN   1652979501
...                                                  ...          ...
30665                                                NaN   1665742007
30666  No misinformation, conspiracies or blatant rumors   1704133469
30667                          Be nice and keep it civil   1652990494
30668  No more than 10 percent of your submissions sh...   1652980368
30669  Adhere to reddiquette and all of reddit's side...   1652980368

                                    rule_prompt
0                  Never let them see you bleed
1      Never get into a car with a strange girl
2           No discriminatory, uncivil comments
3                   No excessive self-promotion
4                       No trolling or spamming
...                                         ...
30665                                  No child
30666                         No misinformation
30667                       No personal attacks
30668                                   No spam
30669                           Don't be a dick

[30670 rows x 9 columns]>

In [10]:
df.shape

(30670, 9)