In [2]:
!pip install pandas

Requirement already satisfied: pandas in d:\study material\python\pandas\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in d:\study material\python\pandas\.venv\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\study material\python\pandas\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\study material\python\pandas\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\study material\python\pandas\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\study material\python\pandas\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('recommendation_logs.csv')

In [5]:
df.head()

,recommendation_id,user_id,movie_id,recommendation_date,recommendation_type,recommendation_score,was_clicked,position_in_list,device_type,time_of_day,algorithm_version
0,rec_000001,user_06326,movie_0771,2025-07-03,new_releases,NaN,False,10,Tablet,evening,v1.4
1,rec_000002,user_02180,movie_0985,2024-11-07,genre_based,0.916,False,9,Mobile,evening,v1.4
2,rec_000003,user_03535,movie_0834,2024-08-22,personalized,0.816,False,2,Tablet,evening,v1.4
3,rec_000004,user_05025,movie_0718,2024-04-12,trending,0.771,False,16,Mobile,evening,v1.2
4,rec_000005,user_06794,movie_0718,2025-10-30,similar_users,0.251,False,9,Tablet,evening,v1.3

In [6]:
df.columns

Index(['recommendation_id', 'user_id', 'movie_id', 'recommendation_date',
       'recommendation_type', 'recommendation_score', 'was_clicked',
       'position_in_list', 'device_type', 'time_of_day', 'algorithm_version'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52000 entries, 0 to 51999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   recommendation_id     52000 non-null  object
 1   user_id               52000 non-null  object
 2   movie_id              52000 non-null  object
 3   recommendation_date   52000 non-null  object
 4   recommendation_type   52000 non-null  object
 5   recommendation_score  46784 non-null  float64
 6   was_clicked           52000 non-null  bool
 7   position_in_list      52000 non-null  int64
 8   device_type           52000 non-null  object
 9   time_of_day           52000 non-null  object
 10  algorithm_version     49380 non-null  object
dtypes: bool(1), float64(1), int64(1), object(8)
memory usage: 4.0+ MB

In [9]:
for col in df.select_dtypes(include='number'):
    df[col].fillna(df[col].mean(), inplace=True)

C:\Users\Simran Kumari\AppData\Local\Temp\ipykernel_11436\331346822.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [10]:
df.shape

(52000, 11)

In [11]:
df.dropna

<bound method DataFrame.dropna of       recommendation_id     user_id    movie_id recommendation_date  \
0            rec_000001  user_06326  movie_0771          2025-07-03
1            rec_000002  user_02180  movie_0985          2024-11-07
2            rec_000003  user_03535  movie_0834          2024-08-22
3            rec_000004  user_05025  movie_0718          2024-04-12
4            rec_000005  user_06794  movie_0718          2025-10-30
...                 ...         ...         ...                 ...
51995        rec_026668  user_01387  movie_0171          2025-08-04
51996        rec_004380  user_09314  movie_0430          2024-04-03
51997        rec_022275  user_02654  movie_0944          2024-06-04
51998        rec_015452  user_04683  movie_0248          2024-05-25
51999        rec_048650  user_04546  movie_0288          2024-07-28

      recommendation_type  recommendation_score  was_clicked  \
0            new_releases              0.551509        False
1             genre_based              0.916000        False
2            personalized              0.816000        False
3                trending              0.771000        False
4           similar_users              0.251000        False
...                   ...                   ...          ...
51995        new_releases              0.126000        False
51996       similar_users              0.192000        False
51997            trending              0.283000        False
51998         genre_based              0.217000         True
51999        new_releases              0.551509        False

       position_in_list device_type time_of_day algorithm_version
0                    10      Tablet     evening              v1.4
1                     9      Mobile     evening              v1.4
2                     2      Tablet     evening              v1.4
3                    16      Mobile     evening              v1.2
4                     9      Tablet     evening              v1.3
...                 ...         ...         ...               ...
51995                11      Mobile   afternoon              v1.4
51996                13      Tablet   afternoon              v1.4
51997                11      Mobile   afternoon              v1.4
51998                 2      Laptop   afternoon              v1.2
51999                16      Tablet     evening              v1.4

[52000 rows x 11 columns]>

In [12]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of       recommendation_id     user_id    movie_id recommendation_date  \
0            rec_000001  user_06326  movie_0771          2025-07-03
1            rec_000002  user_02180  movie_0985          2024-11-07
2            rec_000003  user_03535  movie_0834          2024-08-22
3            rec_000004  user_05025  movie_0718          2024-04-12
4            rec_000005  user_06794  movie_0718          2025-10-30
...                 ...         ...         ...                 ...
51995        rec_026668  user_01387  movie_0171          2025-08-04
51996        rec_004380  user_09314  movie_0430          2024-04-03
51997        rec_022275  user_02654  movie_0944          2024-06-04
51998        rec_015452  user_04683  movie_0248          2024-05-25
51999        rec_048650  user_04546  movie_0288          2024-07-28

      recommendation_type  recommendation_score  was_clicked  \
0            new_releases              0.551509        False
1             genre_based              0.916000        False
2            personalized              0.816000        False
3                trending              0.771000        False
4           similar_users              0.251000        False
...                   ...                   ...          ...
51995        new_releases              0.126000        False
51996       similar_users              0.192000        False
51997            trending              0.283000        False
51998         genre_based              0.217000         True
51999        new_releases              0.551509        False

       position_in_list device_type time_of_day algorithm_version
0                    10      Tablet     evening              v1.4
1                     9      Mobile     evening              v1.4
2                     2      Tablet     evening              v1.4
3                    16      Mobile     evening              v1.2
4                     9      Tablet     evening              v1.3
...                 ...         ...         ...               ...
51995                11      Mobile   afternoon              v1.4
51996                13      Tablet   afternoon              v1.4
51997                11      Mobile   afternoon              v1.4
51998                 2      Laptop   afternoon              v1.2
51999                16      Tablet     evening              v1.4

[52000 rows x 11 columns]>

In [14]:
df.fillna(0)

,recommendation_id,user_id,movie_id,recommendation_date,recommendation_type,recommendation_score,was_clicked,position_in_list,device_type,time_of_day,algorithm_version
0,rec_000001,user_06326,movie_0771,2025-07-03,new_releases,0.551509,False,10,Tablet,evening,v1.4
1,rec_000002,user_02180,movie_0985,2024-11-07,genre_based,0.916000,False,9,Mobile,evening,v1.4
2,rec_000003,user_03535,movie_0834,2024-08-22,personalized,0.816000,False,2,Tablet,evening,v1.4
3,rec_000004,user_05025,movie_0718,2024-04-12,trending,0.771000,False,16,Mobile,evening,v1.2
4,rec_000005,user_06794,movie_0718,2025-10-30,similar_users,0.251000,False,9,Tablet,evening,v1.3
...,...,...,...,...,...,...,...,...,...,...,...
51995,rec_026668,user_01387,movie_0171,2025-08-04,new_releases,0.126000,False,11,Mobile,afternoon,v1.4
51996,rec_004380,user_09314,movie_0430,2024-04-03,similar_users,0.192000,False,13,Tablet,afternoon,v1.4
51997,rec_022275,user_02654,movie_0944,2024-06-04,trending,0.283000,False,11,Mobile,afternoon,v1.4
51998,rec_015452,user_04683,movie_0248,2024-05-25,genre_based,0.217000,True,2,Laptop,afternoon,v1.2
51999,rec_048650,user_04546,movie_0288,2024-07-28,new_releases,0.551509,False,16,Tablet,evening,v1.4