In [2]:
!pip install pandas numpy matplotlib

Requirement already satisfied: pandas in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (2.3.2)
Requirement already satisfied: numpy in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (2.3.3)
Requirement already satisfied: matplotlib in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (3.10.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (4.60.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in d:\study material\python\pandas\ipl 2023 dataset\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [5]:
pd.__version__

'2.3.2'

In [6]:
df = pd.read_csv('each_ball_records.csv')

In [7]:
df.head()

,match_no,ballnumber,inningno,over,outcome,batter,bowler,comment,score
0,1,1,1,0.1,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0
1,1,2,1,0.2,1lb,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, 1 leg bye,",1
2,1,3,1,0.3,0,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, no run,",0
3,1,4,1,0.4,1,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, 1 run,",1
4,1,5,1,0.5,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0

In [8]:
df.columns

Index(['match_no', 'ballnumber', 'inningno', 'over', 'outcome', 'batter',
       'bowler', 'comment', 'score'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17863 entries, 0 to 17862
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   match_no    17863 non-null  int64
 1   ballnumber  17863 non-null  int64
 2   inningno    17863 non-null  int64
 3   over        17863 non-null  float64
 4   outcome     17863 non-null  object
 5   batter      17863 non-null  object
 6   bowler      17863 non-null  object
 7   comment     17863 non-null  object
 8   score       17863 non-null  int64
dtypes: float64(1), int64(4), object(4)
memory usage: 1.2+ MB

In [10]:
type(df["outcome"])

pandas.core.series.Series

In [11]:
new_columns_name = [] 
for i in df.columns:
    new_columns_name.append(i.capitalize())

In [13]:
new_columns_name

['Match_no',
 'Ballnumber',
 'Inningno',
 'Over',
 'Outcome',
 'Batter',
 'Bowler',
 'Comment',
 'Score']

In [14]:
df.columns = new_columns_name
df.head()

,Match_no,Ballnumber,Inningno,Over,Outcome,Batter,Bowler,Comment,Score
0,1,1,1,0.1,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0
1,1,2,1,0.2,1lb,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, 1 leg bye,",1
2,1,3,1,0.3,0,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, no run,",0
3,1,4,1,0.4,1,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, 1 run,",1
4,1,5,1,0.5,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df.isna().sum()

Match_no      0
Ballnumber    0
Inningno      0
Over          0
Outcome       0
Batter        0
Bowler        0
Comment       0
Score         0
dtype: int64

In [18]:
df.fillna(method='ffill', inplace=True)

C:\Users\Simran Kumari\AppData\Local\Temp\ipykernel_8092\3970806690.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

In [19]:
df["Ballnumber"].nunique()

136

In [20]:
df.head(12)

,Match_no,Ballnumber,Inningno,Over,Outcome,Batter,Bowler,Comment,Score
0,1,1,1,0.1,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0
1,1,2,1,0.2,1lb,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, 1 leg bye,",1
2,1,3,1,0.3,0,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, no run,",0
3,1,4,1,0.4,1,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, 1 run,",1
4,1,5,1,0.5,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0
5,1,6,1,0.6,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0
6,1,7,1,1.1,4,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, Four,",4
7,1,8,1,1.2,0,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, no run,",0
8,1,9,1,1.3,4,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, Four,",4
9,1,10,1,1.4,1,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, 1 run,",1
10,1,11,1,1.5,1,Devon Conway,Hardik Pandya,"Hardik Pandya to Devon Conway, 1 run,",1
11,1,12,1,1.6,1,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, 1 run,",1

In [21]:
type(df["Outcome"])

pandas.core.series.Series

In [22]:
df.drop_duplicates(inplace=True)

In [25]:
list(df["Outcome"].unique())

['0',
 '1lb',
 '1',
 '4',
 'w',
 '6',
 '1nb',
 '4lb',
 '2',
 '1b',
 '1wd',
 '2nb',
 '5nb',
 '7nb',
 '3',
 '5wd',
 '4b',
 '2wd',
 '5',
 '3wd',
 '2lb',
 '3nb',
 '2b']

In [30]:
df.to_csv('ipl_2023_cleaned.csv', index=False)

In [32]:
df.head(12)

,Match_no,Ballnumber,Inningno,Over,Outcome,Batter,Bowler,Comment,Score,runs
0,1,1,1,0.1,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0,0
1,1,2,1,0.2,1lb,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, 1 leg bye,",1,0
2,1,3,1,0.3,0,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, no run,",0,0
3,1,4,1,0.4,1,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, 1 run,",1,1
4,1,5,1,0.5,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0,0
5,1,6,1,0.6,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0,0
6,1,7,1,1.1,4,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, Four,",4,4
7,1,8,1,1.2,0,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, no run,",0,0
8,1,9,1,1.3,4,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, Four,",4,4
9,1,10,1,1.4,1,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, 1 run,",1,1
10,1,11,1,1.5,1,Devon Conway,Hardik Pandya,"Hardik Pandya to Devon Conway, 1 run,",1,1
11,1,12,1,1.6,1,Ruturaj Gaikwad,Hardik Pandya,"Hardik Pandya to Ruturaj Gaikwad, 1 run,",1,1

In [40]:
text_cols = ["Outcome", "Comment", "Batter", "Bowler"]
for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

In [42]:
df.head(2)

,Match_no,Ballnumber,Inningno,Over,Outcome,Batter,Bowler,Comment,Score,runs
0,1,1,1,0.1,0,devon conway,Mohammed Shami,"mohammed shami to devon conway, no run,",0,0
1,1,2,1,0.2,1lb,devon conway,Mohammed Shami,"mohammed shami to devon conway, 1 leg bye,",1,0

In [43]:
# same goes with numeric columns
num_col = ["Match_no","Ballnumber", "Inningno", "Over", "Score", "runs"]
for col in num_col:
    df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)

In [44]:
df.to_csv('ipl_2023_cleaned_new.csv', index=False)